
name: Super-Linter

on:
  push:
   branches: [ "demo_branch" ]
  pull_request:
    branches: [ "note_branch" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Super-Linter
      - uses: github/super-linter@v4.10.0
