name: Lint Code Base

on:
  push:
   branches: [ "demo_branch" ]
  pull_request:
    branches: [ "note_branch" ]
jobs:
  vue-tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: keita-hino/vue-tsc-action@main
       
