
name: Lint Code Base

on:
  push:
     branches: [ "note_branch" ,"notes" ]
  pull_request:
    branches: [ "note_branch" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: github/super-linter@v4.10.0
    env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "notes"
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_CSS: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSON: false
        
