name: Lint Code Base

on:
  push:
   branches: [ "test_branch" ]
  pull_request:
    branches: [ "note_branch" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: github/super-linter@v4.10.0
