name: Lint Code Base

on:
  push:
   branches: [ "vue_test_branch" ]
  pull_request:
    branches: [ "note_branch" ]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: github/super-linter@v4.10.0
      - name: vue-tsc-action
        uses: keita-hino/vue-tsc-action@v0.1.1
       
