
name: Linter

on:
  push:
    branches: [ "notes" ]
  pull_request:
    branches: [ "notes" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Super-Linter
          uses: github/super-linter@v4.10.0
